services:
  cockroach:
    image: cockroachdb/cockroach:v24.2.4
    # Data persistency disabled for testing purporses
    # volumes:
      # - "roach-data:/cockroach/cockroach-data"
    environment:
      - 'COCKROACH_DATABASE=awesomepizza'
      - 'COCKROACH_USER=myuser'
      - 'COCKROACH_PASSWORD=secret'
    ports:
      - '26257:26257'
      - '8081:8080' # Web console
    command: start-single-node --http-addr=cockroach:8080 --accept-sql-without-tls

volumes:
  roach-data:
